### PR TITLE
Switched to communitheme-icon-theme for cursors

### PR DESCRIPTION
**Pull request by merlijn-sebrechts**
This way, we retain backwards compatibility with the session file in Ubuntu 18.04 while switching to the Suru cursor theme.

### CODE REVIEW

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/communitheme-snap-helpers-pr13`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/communitheme-snap-helpers-pr13` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by merlijn-sebrechts** [comment]
Hm, it's strange, the snap in `edge/communitheme-snap-helpers-pr13` doesn't include my changes

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/communitheme-snap-helpers-pr13`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/communitheme-snap-helpers-pr13` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by didrocks** [comment]
A new test snap version is available using: `snap refresh communitheme --channel=edge/communitheme-snap-helpers-pr13`.
Further available updates will track that pull request then.

Switch back to stable or edge snap with `snap refresh communitheme --stable` or `snap refresh communitheme --edge` once you are done with it!
You may want to download as well `gtk-common-themes` snap from `edge/communitheme-snap-helpers-pr13` channel to test your snaps with those changes.

Replace `refresh` with `install` if you haven't installed the snap yet.

**Comment by merlijn-sebrechts** [comment]
I fixed the PR builder, now the correct snap is published. However, I found another issue with the communitheme-icon-theme repo: it used `Communitheme` instead of `communitheme` as name for the cursor theme, so don't merge this PR until that is fixed.

**Comment by didrocks** [comment]
Thanks for the fixes to pick the current script and yaml. I used to change the env variable to this repo, but this is way better :)
I would prepare to thave the 2 changes separated in 2 PR if possible.

Some questions on the other one:
- I thought the cursor theme was part of the Suru icon theme itself, so why another repo?
- I why creating another repo? If this is the way we go, maybe reuse the other one? (via git push -f). Or we can even remove the other repo, as needed.

Nitpick: I would put `meson-paramer` before `stage`, as this happens before, (for readability)

**Comment by merlijn-sebrechts** [comment]
Ok, I'l separate them into two PR's

My reasoning for the new repo:

- We can't use the `suru-icon-theme` repo because the cursor theme in that repo is called `Suru`, not `communitheme`, like the communitheme session requests.
- We could move all the cursor bits to a different folder in the `suru-icon-theme` repo and rename it to `communitheme` but this will totally trip up git merges when we sync with the upstream suru-icon-theme repo.
- We could reuse the `communitheme-cursors` repo, but then we'll overwrite the current cursors and they aren't backed up anywhere else (mads original repo has diverged too much to simply merge them back in). Moreover, the cursor theme repo is forked from `madsrh/yet-another-DMZ-cursor-theme`, which gives the wrong impression, and which trips up Github (for example, Github requests pull requests to the madsrh repo).
- Since the cursor theme and the icon theme are already in a single repo, the name `communitheme-cursors` wouldn't be accurate anymore, and isn't future-proof since, ideally, we want to go to a single repo for both the icon and the cursor theme (but then both named `<our-awesome-name>`).
- We've been talking about actually forking and renaming Suru, so the `communitheme-icon-theme` repo enables us to do that in a backwards-compatible way: `suru-icon-theme` is maintained until we update the session to point to the icon and cursor theme in `communitheme-icon-theme` (which will then be called `<our-awesome-name>-icon-theme`.)

**Comment by didrocks** [comment]
If the content is in `suru-icon-theme`, I don't think we should create yet another fork which will be the same content. It's additional maintenance we shouldn't commit on. And it seems you agree with "we want to go to a single repo". So let's reuse our fork for now until we get the finale name out ;)

There are multiple fixes for the issues you mention (pointing to the directory Communitheme):
- creating a relative symlink
- renaming at packaging time (in snapraft.yaml) the cursor directory.

Both will be fine with our current "intermediate" state, and we can remove both *cursor* repos, only having 4. WDYT?

**Comment by merlijn-sebrechts** [comment]
That sound good, I think a symlink is the ideal approach, I'll see if I can get that to work.

**Comment by didrocks** [comment]
Look at https://github.com/ubuntu/communitheme-snap-helpers/blob/master/build/gtk-common-themes-parts.yaml#L6 to run scripts during snapcraft build.

**Pull request closed without merging**
